### ISSUE TITLE
[V] kekw emoji

### ISSUE THREAD

**Issue by lus** [dev-schueppchen/suggestions#3]
# Kekw-Emoji

> Lukaesebrot#8001

## Kurzbeschreibung
*Wir brauchen einen nicht-animierten Kekw-Emoji für nicht-Nitro-Leute*

## Lösung / Vorschlag
*Wir brauchen einen nicht-animierten Kekw-Emoji für nicht-Nitro-Leute*

**Comment by zekroTJA** [comment]
Buy nitro.

If you don't have money:
Buy money.

**Comment by zekroTJA** [comment]
![image](https://user-images.githubusercontent.com/16734205/106024066-ad77cc80-60c7-11eb-85f3-259183fe7a96.png)
